inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 132 # good for desktop Github

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/IndentArray:
  EnforcedStyle: consistent

Naming/FileName:
  Exclude:
    - Dangerfile

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Rails/FilePath:
  Enabled: false

AllCops:
  Exclude:
    - Gemfile
    - vendor/**/*
    - node_modules/**/*
    - bin/webpack*
