#! /bin/bash -e

if git remote | grep -v heroku; then
  exit 0
fi

git fetch heroku
heroku pg:backups:capture
git push --force heroku $CIRCLE_SHA1:master
heroku run --exit-code rake db:migrate
heroku restart
