#! /bin/bash -e

if [ "${CIRCLE_BRANCH}" == "master" ]; then
  app_name=rosalind-staging
elif [ "${CIRCLE_BRANCH}" == "release" ]; then
  app_name=rosalind-production
else
  exit 0
fi

git fetch heroku
heroku pg:backups:capture
git push --force heroku $CIRCLE_SHA1:master
heroku run --exit-code rake db:migrate
heroku restart
