development: &default
  url: <%= ENV['SEARCH_URL'] || ENV['ELASTICSEARCH_URL'] || 'http://localhost:9200' %>
  index: <%= ENV['SEARCH_INDEX'] || ENV['ELASTICSEARCH_INDEX'] || 'gravity' %>
test:
  <<: *default
production:
  <<: *default
