---
version: '2'
services:
  rosalind:
    command: sh -c 'bundle exec rails db:migrate && bundle exec puma -C config/puma.config'
    env_file: ../.env
    extends:
      file: build.yml
      service: rosalind
    ports:
      - 5000:5000
    volumes:
      - ../:/app
    depends_on:
      - rosalind-postgres
      - rosalind-redis
    environment:
      - DATABASE_URL=postgresql://postgres:@rosalind-postgres/rosalind_development
      - RAILS_ENV=development
      - REDIS_URL=redis://rosalind-redis
  worker:
    extends:
      file: build.yml
      service: rosalind
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres:@rosalind-postgres/rosalind_development
      - REDIS_URL=redis://rosalind-redis
    env_file: ../.env
    command: bundle exec sidekiq
    depends_on:
      - rosalind-postgres
      - rosalind-redis
  rosalind-postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=rosalind_development
      - PGDATA=/tmp
  rosalind-redis:
    image: redis:3.2-alpine
