---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rosalind-web
  namespace: default
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rosalind
        component: web
        layer: application
      name: rosalind-web
      namespace: default
    spec:
      containers:
        - name: rosalind-web
          env:
            - name: PORT
              value: "8080"
            - name: RAILS_ENV
              value: production
            - name: RAILS_SERVE_STATIC_FILES
              value: 'true'
            - name: RAILS_LOG_TO_STDOUT
              value: 'true'
            - name: PUMA_BIND
              value: 'tcp://0.0.0.0:8080'
            - name: TRACE_AGENT_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MALLOC_ARENA_MAX
              value: "2"
          envFrom:
            - configMapRef:
                name: rosalind-environment
          image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/rosalind:production
          imagePullPolicy: Always
          ports:
            - name: rosalind-http
              containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              memory: 512Mi
          readinessProbe:
            httpGet:
              port: rosalind-http
              path: /health/ping
              httpHeaders:
                - name: X-Forwarded-Proto
                  value: https
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: tier
                  operator: In
                  values:
                    - foreground
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rosalind-web
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: rosalind-web
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rosalind-sidekiq
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: rosalind-sidekiq
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rosalind-sidekiq
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rosalind
        layer: application
        component: sidekiq
      name: rosalind-sidekiq
      namespace: default
    spec:
      containers:
        - name: rosalind-sidekiq
          env:
            - name: RAILS_LOG_TO_STDOUT
              value: 'true'
            - name: TRACE_AGENT_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MALLOC_ARENA_MAX
              value: "2"
          envFrom:
            - configMapRef:
                name: rosalind-environment
          image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/rosalind:production
          imagePullPolicy: Always
          args: ["bundle", "exec", "sidekiq"]
          livenessProbe:
            exec:
              command:
                - pgrep
                - -f
                - sidekiq
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              memory: 512Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: tier
                    operator: In
                    values:
                      - background

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rosalind
    component: web
    layer: application
  name: rosalind-web-internal
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: http
      targetPort: 8080
  selector:
    app: rosalind
    layer: application
    component: web
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rosalind
spec:
  rules:
    - host: rosalind.artsy.net
      http:
        paths:
          - path: /
            backend:
              serviceName: rosalind-web-internal
              servicePort: http
