---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rosalind-web
  namespace: default
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rosalind
        component: web
        layer: application
      name: rosalind-web
    spec:
      containers:
        - name: rosalind-web
          env:
            - name: RAILS_ENV
              value: production
            - name: RAILS_SERVE_STATIC_FILES
              value: 'true'
            - name: RAILS_LOG_TO_STDOUT
              value: 'true'
            - name: PUMA_BIND
              value: 'tcp://0.0.0.0:8080'
            - name: TRACE_AGENT_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          envFrom:
            - configMapRef:
                name: rosalind-environment
          image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/rosalind:production
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 500Mi
          readinessProbe:
            httpGet:
              port: 8080
              path: /health/ping
              httpHeaders:
                - name: X-Forwarded-Proto
                  value: https
            initialDelaySeconds: 10
            periodSeconds: 10
        - name: rosalind-nginx
          image: artsy/docker-nginx:1.14.2
          ports:
            - containerPort: 80
            - containerPort: 443
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 10
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx", "-s", "quit"]
          env:
            - name: 'NGINX_DEFAULT_CONF'
              valueFrom:
                configMapKeyRef:
                  name: nginx-config
                  key: default
          volumeMounts:
            - name: nginx-secrets
              mountPath: /etc/nginx/ssl
      volumes:
        - name: nginx-secrets
          secret:
            secretName: nginx-secrets
            defaultMode: 420
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: tier
                  operator: In
                  values:
                    - foreground
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rosalind
    component: web
    layer: application
  name: rosalind-web
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:iam::585031190124:server-certificate/2018-01-17_artsy-net-wildcard"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
      targetPort: 80
    - port: 443
      protocol: TCP
      name: https
      targetPort: 443
  selector:
    app: rosalind
    layer: application
    component: web
  sessionAffinity: None
  type: LoadBalancer
