---
version: '2'
services:
  rosalind:
    command: ./hokusai/ci.sh
{% include 'templates/docker-compose-service.yml.j2' %}
    depends_on:
      - rosalind-postgres
    environment:
      - RAILS_ENV=test
      - DATABASE_URL=postgresql://postgres:@rosalind-postgres/rosalind_test
  rosalind-postgres:
    image: postgres:12.5-alpine
    environment:
      - POSTGRES_DB=rosalind_test
      - POSTGRES_HOST_AUTH_METHOD=trust
